publish:
  name: "Publish to GitHub Packages"
  needs: [package]
  runs-on: ubuntu-18.04
  if: github.repository_owner == 'square-bit'
  steps:
    - name: Upload
      uses: actions/download-artifact@v2
      with:
        name: package
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: https://npm.pkg.github.com/
        scope: "@square-bit"
    - run: echo "registry=https://npm.pkg.github.com/@square-bit" >> .npmrc
    - run: npm publish $(ls *.tgz)
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}